server:
  port: 8080

spring:
  application:
    name: registro-app
  datasource:
    url: jdbc:postgresql://localhost:5432/root
    username: postgres
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  main:
    web-application-type: servlet
